### ISSUE TITLE
Custom schema resets and clears out edits

### ISSUE THREAD

**Issue by davidnmargulies** [tinybirdco/mockingbird#28]
When editing a schema, sometimes the predefined schema is reset. Clicking 'save' again clears out any edits, making it incredibly frustrating to modify an existing schema.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/105812959/229858069-fb4c96ab-27ef-4d6d-9383-9d410f4a8be7.png">

**Comment by sdairs** [comment]
@davidnmargulies this should also be resolved - lmk if we need to re-open
