### ISSUE TITLE
Pasting a schema in "text" does not allow you to save

### ISSUE THREAD

**Issue by davidnmargulies** [tinybirdco/mockingbird#29]
I attempted to copy and paste a schema in the "text" option, but it did not allow me to save.

https://user-images.githubusercontent.com/105812959/229859246-f3e8b7d2-e13d-46eb-bb84-57458aa0b99d.mov

**Comment by sdairs** [comment]
@davidnmargulies this should be resolved now - lmk if you hit it again & we can re-open
