### ISSUE TITLE
Issue with upstash-kafka

### ISSUE THREAD

**Issue by SichikUA** [tinybirdco/mockingbird#77]
Hi there!

Im trying to generate events to upstash-kafka destination.
Upstash kafka topic was created, and it were receiving events using pure Producer RESR API with success.

But
- If i am trying mockingbird Cloud UI or Local UI - i got failed requests (to https://fit-mallard-XXXXX-eu2-kafka.upstash.io:9092/produce/Orders) in my browser console with no any HTTP status .
- If I am trying CLI:  mockingbird-cli  upstash-kafka --address=https://fit-mallard-XXXXX-eu2-kafka.upstash.io:9092/ --user=XXXXXX --pass=XXXXXX --topic=Orders --eps=1 --limit=-1 --schema=/Users/vadym/development/mockingbird/schemas/schema.json 
i got Upstash Error: {"message":"request to https://fit-mallard-XXXXX-eu2-kafka.upstash.io:9092/produce/Orders failed, reason: socket hang up","type":"system","errno":"ECONNRESET","code":"ECONNRESET"}.

do i do something wrong or it is some issue?

**Comment by sdairs** [comment]
Thanks @SichikUA - we'll investigate this!

**Comment by sdairs** [comment]
Upstash Kafka has been removed as Upstash has deprecated their Kafka service
